### ISSUE TITLE
Sidekiq crashes

### ISSUE THREAD

**Issue by wilco375** [csvalpha/sofia#903]
All Sidekiq containers are currently in a restart loop due to the following error. Because of this no jobs, such as sending invoices and low balance emails, are currently being executed. Looking at the production container, this has been an issue for at least two weeks. I tried to find a hotfix but could not quickly get one working.
```
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      minitest (>= 5.1)
      Available/installed versions of this gem:
      - 5.18.0
      - 5.16.3
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/runtime.rb:302:in `check_for_activated_spec!': You have already activated digest 3.1.1, but your Gemfile requires digest 3.1.0. Since digest is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports digest as a default gem. (Gem::LoadError)
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/runtime.rb:31:in `block in setup'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/spec_set.rb:152:in `each'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/spec_set.rb:152:in `each'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/runtime.rb:26:in `map'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/runtime.rb:26:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler.rb:148:in `setup'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:136:in `with_level'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:88:in `silence'
        from /usr/local/bundle/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
        from /app/config/boot.rb:3:in `<top (required)>'
        from /app/config/application.rb:1:in `require_relative'
        from /app/config/application.rb:1:in `<top (required)>'
        from /app/config/environment.rb:2:in `require_relative'
        from /app/config/environment.rb:2:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:148:in `require'
        from /usr/local/bundle/gems/sidekiq-7.0.9/lib/sidekiq/cli.rb:302:in `boot_application'
        from /usr/local/bundle/gems/sidekiq-7.0.9/lib/sidekiq/cli.rb:42:in `run'
        from /usr/local/bundle/gems/sidekiq-7.0.9/bin/sidekiq:31:in `<top (required)>'
        from /usr/local/bundle/bin/sidekiq:25:in `load'
        from /usr/local/bundle/bin/sidekiq:25:in `<main>'
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

**Comment by lodewiges** [comment]
can i close this, it sees to be working now
